apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-env
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_BASE_URL: {{ .Values.env.NEXT_PUBLIC_API_BASE_URL | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}